name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  job1:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status check
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Super-linter
        uses: super-linter/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: '(\.gradle/|\.idea/|\.github/|\build|\gradle|\gradlew|\gradle.properties|\app\google_services.json)'

          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
  job2:
    needs: job1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload QA Flavour APK to Firebase App Tester
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: qa-internal
          releaseNotes: "releaseNotes.txt"
          file: app/build/outputs/apk/debug/app-debug.apk
